spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

application:
  baseUrl: ${APP_BASE_URL}