--
-- This migration scripts aims to create the URL_ENTRY table and define its constraints.
--
CREATE TABLE URL_ENTRY (
    ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    URL_ADDRESS VARCHAR(2000) NOT NULL,
    CREATED_AT DATETIME NOT NULL
);

ALTER TABLE URL_ENTRY
ADD CONSTRAINT UNQ_URL_ENTRY_URL_ADDRESS
UNIQUE(URL_ADDRESS);